# Generated by Django 5.1.6 on 2025-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project8',
            options={'ordering': ['-created'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='project8',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacíón'),
        ),
        migrations.AlterField(
            model_name='project8',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project8',
            name='image',
            field=models.ImageField(upload_to='projects', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='project8',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='project8',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición'),
        ),
    ]
